site_name: 'Vladimir lab'  
site_author: Vladimir
site_description: PRAC2 custom theme

theme:
  name: null
  custom_dir: 'statics'

extra_css:
  - css/stlyles.css

docs_dir: docs
nav:  
  - Главная: index.md
  - Обо мне: about/index.md
  - Контакты: contact/index.md